#1228 - Update to Node 12.16.0
mojaloop/central-services-health pull request #137
Opened 2020-02-12 16:47 UTC by oderayi

- Use Node 12.16.0 in CircleCI 
- Updated dependencies

2020-02-12 17:36 UTC, yosheeck approved these changes

2020-02-13 09:22 UTC, lewisdaly requested changes
I think we need to be updating hapi

2020-02-13 09:22 UTC, lewisdaly commented on .ncurc.json
> +    "@hapi/hapi"
I think we should be updating hapi here. Was there any reason not to?

2020-02-13 11:55 UTC, rmothilal approved these changes
Hapi

2020-02-13 12:46 UTC, merged